### ISSUE TITLE
Use 7 as the default short SHA

### ISSUE THREAD

**Issue by ghost** [benjlevesque/short-sha#10]
Github and Git SCM's "Pro Git" book both use a short SHA 7 characters long:

- https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_short_sha_1
- https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/viewing-the-branch-history
- https://docs.github.com/en/github/committing-changes-to-your-project/viewing-and-comparing-commits/commit-branch-and-tag-labels

**Comment by benjlevesque** [comment]
Good point! Actually the README was wrong, and the default value is already 7... https://github.com/benjlevesque/short-sha/blob/master/action.yml#L10

I fixed the README, thanks for reporting this!
