### ISSUE TITLE
Still getting the warning to upgrade from Node 12 to 16

### ISSUE THREAD

**Issue by kr185198** [benjlevesque/short-sha#12]
**Build Branch**
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: benjlevesque/short-sha

**Comment by benjlevesque** [comment]
which version are you using please?

**Comment by kr185198** [comment]
uses: benjlevesque/short-sha@v1.2

getting the following error when used with v2:
**Error: Unable to resolve action `benjlevesque/short-sha@v2`, unable to find version `v2**

**Comment by benjlevesque** [comment]
my bad, it should `v2.0`, I'll update the README

**Comment by kr185198** [comment]
okay. thanks. It worked.
