### ISSUE TITLE
Warning `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by xanderhendriks** [benjlevesque/short-sha#13]
I get the following warning in my builds that use this action: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I tried updating the dependencies with yarn in a [fork](https://github.com/xanderhendriks/short-sha/) of the repo, but this didn't solve the issue. I expect the index.js requires updating, but I'm not quite sure how.

**Comment by cpavlatos** [comment]
bump...I get the same warning.

**Comment by xanderhendriks** [comment]
@benjlevesque now that I worked out that I missed a step when updating the dependencies, I have regenerated the code in a [pull request](https://github.com/benjlevesque/short-sha/pull/14)

**Comment by benjlevesque** [comment]
solved by #14 , thank you @xanderhendriks 

Please update to `v2.1`
