### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by murfee25** [benjlevesque/short-sha#17]
Just noticed this warning using this step in my github workflow.

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Do you have plans to upgrade the use of 'set-output' ?

**Comment by benjlevesque** [comment]
Hello @murfee25, 
Which version are you using? This issue was raised in #13 , and resolved in [v2.1](https://github.com/benjlevesque/short-sha/releases/v2.1)

**Comment by murfee25** [comment]
Hi @benjlevesque,
Thanks for your response. I am using v1.2 so I will get that updated to v2.1. 👍 

I got v1.2 from the github actions marketplace when you click on the `Use latest version` button so I guess I shouldn't trust that to necessarily be the latest.

Thanks again.

**Comment by benjlevesque** [comment]
Oh ok, I'll see if I can change that 
Thank you!
