### ISSUE TITLE
Update node version 16 to 20

### ISSUE THREAD

**Issue by KirillHouras** [benjlevesque/short-sha#18]
Necessary to update node version 16 to 20, because Node 16 has reached its end of life and github command want to transition all actions to run on Node 20 by Spring 2024: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by lumapu** [comment]
would be nice if the PR could be merged, the annotations logs are flooded with deprecation warnings
