### ISSUE TITLE
How to use short "SHA" value in "run-name"?

### ISSUE THREAD

**Issue by NianBroken** [benjlevesque/short-sha#20]
I need to use "SHA" in "run-name" for bug detection, but the default "SHA" is too long, and it's very hard to read, especially on the It's very hard to read, especially on cell phones. So I need to use short "SHA", but when I use short "SHA" in "run-name", Workflow will report an error.

The error log is shown below:

```bash
Invalid workflow file: .github/workflows/main.yml#L1
The workflow is not valid. .github/workflows/main.yml (Line: 19, Col: 11): Unrecognized named-value: 'env'. Located at position 1 within expression: env.SHA
```

![image](https://github.com/benjlevesque/short-sha/assets/57057288/b1d09171-c9ca-47e6-ba38-7e9232b7cb12)
![image](https://github.com/benjlevesque/short-sha/assets/57057288/15d2e34f-3e68-401c-8d75-e33e240ffefb)
![image](https://github.com/benjlevesque/short-sha/assets/57057288/ac4d2553-94c6-4d56-998a-556032011877)
![image](https://github.com/benjlevesque/short-sha/assets/57057288/da075842-5c34-4569-90d9-79410d7de4e2)

**Comment by NianBroken** [comment]
@benjlevesque @filariow @xanderhendriks @KirillHouras 
I am in dire need of a tutorial on using short "SHA" in "run-name".
I desperately need a tutorial on how to use short "SHA" in "run-name".

**Comment by filariow** [comment]
From docs (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) it seems you can only use [inputs](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context) and [github](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) context.

 Hence, it seems to me, you cannot make use of data provided by this action for the field run-name.

You may be interested in using the full SHA. You have that in `github.sha`.

**Comment by xanderhendriks** [comment]
I personally don't use this action anymore, but just run sed to grab the info I need from `github.sha`. Have a look here to see if that helps you: https://github.com/xanderhendriks/stm32-sample-application/blob/master/.github/workflows/continuous_integration_pipeline.yml#L41

**Comment by benjlevesque** [comment]
I agree with @filariow, I don't think this is possible. @xanderhendriks' approach could be the right approach 👍

**Comment by NianBroken** [comment]
Can you give me an example of using a short "SHA" in "run-name"? I really need this code example.
@benjlevesque @filariow @xanderhendriks @KirillHouras

**Comment by xanderhendriks** [comment]
Did the solution I proposed not work? Do you have a link to a public repo that shows an error with it?

**Comment by NianBroken** [comment]
> Did the solution I proposed not work? Do you have a link to a public repo that shows an error with it?

https://github.com/BreakNian/TEST/blob/main/.github/workflows/main.yml
@benjlevesque @filariow @xanderhendriks @KirillHouras

**Comment by NianBroken** [comment]
@xanderhendriks I've added you as a Collaborator.

![image](https://github.com/benjlevesque/short-sha/assets/57057288/57e45b15-3b68-4341-aa3d-0125e689af26)

**Comment by NianBroken** [comment]
@torbjornvatn

**Comment by xanderhendriks** [comment]
I guess I should have known, it only runs a shell when you are inside a step. So for the command I proposed it shows the command and the actual full commit hash.
Looking at the manuals there doesn't seem to be any kind of string manipulation build into the yml file parser, so I think what you are trying to do just can't be done.
![image](https://github.com/benjlevesque/short-sha/assets/57311059/cab6b042-ad4f-462c-b386-458599e3deef)
